### PR TITLE
packages update

### PR DESCRIPTION
**Pull request by SychevIgor**
Packages versions updated.
format of Microsoft.Azure.Devices.Client" Version across all projects standardized

### CODE REVIEW

**Comment by MikeBazMSFT** [comment]
Hmm, why are some packages changed to wildcard version 1.* but others have specific references?  That feels inconsistent.  It should be all wildcard 1.* or all specific.

**Comment by SychevIgor** [comment]
if it's ok to use 1.* in every package- ok, I'm happy to update PR.

**Comment by MikeBazMSFT** [comment]
I didn't completely test end to end, but it does build with the wildcard successfully on all references, and I believe that matches the spirit of your original PR?

**Comment by ChrisHowd** [comment]
We are currently reworking the code projects for the labs and will incorporate these changes when we release the update.

**Pull request closed without merging**
